export const PRODUCTS = [
  {
    id: 1,
    name: 'Toor Dal / Thuvaram Paruppu',
    category: 'Dal & Pulse',
    Img: require('../assets/images/ToorDal.jpg'),
    type: 1,
    pricePerKg: '132',
    quantity: 0,
    Qty: '1 Kg',
  },
  {
    id: 2,
    name: 'Jeeragam',
    category: 'Oil & Ghee',
    Img: require('../assets/images/Jeeragam.png'),
    type: 1,
    pricePerKg: '440',
    quantity: 0,
    Qty: '1 Kg',
  },
  {
    id: 3,
    name: 'Sombu',
    category: 'Oil & Ghee',
    Img: require('../assets/images/Sombu.jpg'),
    type: 1,
    pricePerKg: '300',
    quantity: 0,
    Qty: '1 Kg',
  },
  {
    id: 4,
    name: 'Milagu',
    category: 'Rice & Flour',
    Img: require('../assets/images/Milagu.png'),
    type: 1,
    pricePerKg: '700',
    quantity: 0,
    Qty: '1 Kg',
  },
  {
    id: 5,
    name: 'ChannaDal',
    category: 'Dry Fruit & nut',
    Img: require('../assets/images/ChanaDal.jpg'),
    type: 1,
    pricePerKg: '85',
    quantity: 0,
    Qty: '1 Kg',
  },
  {
    id: 6,
    name: 'MoongDal',
    category: 'Body Care',
    Img: require('../assets/images/MoongDal.jpg'),
    type: 1,
    pricePerKg: '115',
    quantity: 0,
    Qty: '1 Kg',
  },
  {
    id: 7,
    name: 'MoongDal',
    category: 'Home Care',
    Img: require('../assets/images/MoongDal.jpg'),
    type: 1,
    pricePerKg: '115',
    quantity: 0,
    Qty: '1 Kg',
  },
  {
    id: 8,
    name: 'MoongDal',
    category: 'Masala & Spices',
    Img: require('../assets/images/MoongDal.jpg'),
    type: 1,
    pricePerKg: '115',
    quantity: 0,
    Qty: '1 Kg',
  },
];

export const CATEGORIES = [
  {
    id: 1,
    name: 'Rice & Flour',
    img: require('../assets/icons/grocery.png'),
  },
  {
    id: 2,
    name: 'Dal & Pulse',
    img: require('../assets/icons/grocery.png'),
  },
  {
    id: 3,
    name: 'Oil & Ghee',
    img: require('../assets/icons/grocery.png'),
  },
  {
    id: 4,
    name: 'Masala & Spices',
    img: require('../assets/icons/grocery.png'),
  },
  {
    id: 5,
    name: 'Dry Fruit & nut',
    img: require('../assets/icons/grocery.png'),
  },
  {
    id: 6,
    name: 'Body Care',
    img: require('../assets/icons/grocery.png'),
  },
  {
    id: 7,
    name: 'Home Care',
    img: require('../assets/icons/grocery.png'),
  },
];
